// Code generated by ddbgen. DO NOT EDIT.

package schema

import (
	_ "embed"

	"github.com/acksell/bezos/dynamodb/schema"
	"gopkg.in/yaml.v3"
)

//go:embed schema_dynamodb.yaml
var schemaYAML []byte

// Schema contains the DynamoDB table and entity definitions for this package.
// Pass this to ddbui.NewServer to enable schema-aware debugging UI.
var Schema schema.Schema

func init() {
	if err := yaml.Unmarshal(schemaYAML, &Schema); err != nil {
		panic("ddbgen: failed to parse embedded schema: " + err.Error())
	}
}
