package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/acksell/bezos/dynamodb/ddbstore"
	"github.com/acksell/bezos/dynamodb/ddbui"
)

func runUI() error {
	fs := flag.NewFlagSet("ui", flag.ExitOnError)

	var (
		dbPath = fs.String("db", "", "path to database directory")
		port   = fs.Int("port", 3070, "HTTP port")
		memory = fs.Bool("memory", false, "use in-memory database (no persistence)")
	)

	fs.Usage = func() {
		fmt.Println(`ddb ui - Start the local debugging UI

Usage:
  ddb ui [flags]

Flags:`)
		fs.PrintDefaults()
		fmt.Println(`
Examples:
  ddb ui --db ./data               # Use local database directory
  ddb ui --memory                  # Use in-memory database (no persistence)
  ddb ui --db ./data --port 9000   # Custom port

Configuration file (ddb.ui.yaml):
  dataDir: ./data
  port: 3070

Schema files are auto-discovered by searching for files containing
"# Generated by ddbgen" header.

The UI provides:
  - Table and entity schema visualization
  - Data browsing with scan and query
  - Item creation, editing, and deletion
  - GSI query support`)
	}

	if err := fs.Parse(os.Args[1:]); err != nil {
		return err
	}

	cfg := LoadUIConfig()

	// Determine database path
	dataDir := *dbPath
	if *memory {
		dataDir = ""
	} else if dataDir == "" {
		dataDir = cfg.DataDir
	}

	// Require database path unless --memory
	if dataDir == "" && !*memory {
		return fmt.Errorf(`database path required

Provide via flag:
  ddb ui --db ./path/to/data

Or create ddb.ui.yaml:
  dataDir: ./path/to/data
  port: 3070

For in-memory (no persistence):
  ddb ui --memory`)
	}

	// Determine port
	serverPort := *port
	if cfg.Port != 0 && *port == 3070 {
		// Use config port if flag wasn't explicitly set
		serverPort = cfg.Port
	}

	// Auto-discover schema files
	schemaFiles, err := DiscoverSchemas()
	if err != nil {
		return fmt.Errorf("discovering schemas: %w", err)
	}
	if len(schemaFiles) == 0 {
		return fmt.Errorf(`no schema files found

Generate schema files with:
  //go:generate ddb gen
  go generate ./...

Schema files must contain the header:
  # Generated by ddbgen. DO NOT EDIT.`)
	}

	fmt.Printf("ddb ui: found %d schema file(s)\n", len(schemaFiles))

	// Load schemas from YAML files
	schemas, err := ddbui.LoadSchemaFilesRaw(schemaFiles)
	if err != nil {
		return fmt.Errorf("loading schemas: %w", err)
	}

	// Extract table definitions for ddbstore
	tableDefs := ddbui.TableDefinitionsFromSchemas(schemas...)

	// Create ddbstore
	storeOpts := ddbstore.StoreOptions{
		Path:     dataDir,
		InMemory: *memory || dataDir == "",
	}
	store, err := ddbstore.New(storeOpts, tableDefs...)
	if err != nil {
		return fmt.Errorf("creating store: %w", err)
	}
	defer store.Close()

	// Create server
	server, err := ddbui.NewServer(store, serverPort, schemas...)
	if err != nil {
		return err
	}

	return server.Run()
}
