package main

import (
	"context"
	"flag"
	"fmt"
	"os"

	"github.com/acksell/bezos/dynamodb/ddbstore"
	"github.com/acksell/bezos/dynamodb/ddbui"
	"github.com/acksell/bezos/dynamodb/schema"
)

func runUI() error {
	fs := flag.NewFlagSet("ui", flag.ExitOnError)

	var (
		dbPath   = fs.String("db", "", "path to database directory")
		port     = fs.Int("port", 3070, "HTTP port")
		memory   = fs.Bool("memory", false, "use in-memory database (no persistence)")
		useAWS   = fs.Bool("aws", false, "connect to real AWS DynamoDB")
		region   = fs.String("region", "", "AWS region (implies --aws)")
		profile  = fs.String("profile", "", "AWS profile name (implies --aws)")
		endpoint = fs.String("endpoint", "", "custom DynamoDB endpoint URL (implies --aws)")
	)

	fs.Usage = func() {
		fmt.Println(`ddb ui - Start the DynamoDB debug UI

Usage:
  ddb ui [flags]

Flags:`)
		fs.PrintDefaults()
		fmt.Println(`
Local mode (default):
  ddb ui --db ./data               # Use local database directory
  ddb ui --memory                  # Use in-memory database (no persistence)
  ddb ui --db ./data --port 9000   # Custom port

AWS mode:
  ddb ui --aws                     # Use default AWS credentials
  ddb ui --aws --region us-east-1  # Explicit region
  ddb ui --aws --profile staging   # Specific AWS profile
  ddb ui --endpoint http://localhost:8000  # DynamoDB-compatible endpoint

Configuration file (ddb.ui.yaml):
  dataDir: ./data
  port: 3070

Schema files are auto-discovered by searching for files containing
"# Generated by ddbgen" header. In AWS mode, schemas are optional;
tables without schemas are auto-discovered via DescribeTable.

The UI provides:
  - Table and entity schema visualization
  - Data browsing with scan and query
  - Item creation, editing, and deletion
  - GSI query support`)
	}

	if err := fs.Parse(os.Args[1:]); err != nil {
		return err
	}

	cfg := LoadUIConfig()

	// --region, --profile, or --endpoint imply --aws
	if *region != "" || *profile != "" || *endpoint != "" {
		*useAWS = true
	}

	// Determine port
	serverPort := *port
	if cfg.Port != 0 && *port == 3070 {
		serverPort = cfg.Port
	}

	if *useAWS {
		return runUIAWS(serverPort, *region, *profile, *endpoint)
	}
	return runUILocal(serverPort, *dbPath, *memory, cfg)
}

// runUILocal starts the UI backed by a local BadgerDB store (existing behavior).
func runUILocal(serverPort int, dbPath string, memory bool, cfg UIConfig) error {
	dataDir := dbPath
	if memory {
		dataDir = ""
	} else if dataDir == "" {
		dataDir = cfg.DataDir
	}

	if dataDir == "" && !memory {
		return fmt.Errorf(`database path required

Provide via flag:
  ddb ui --db ./path/to/data

Or create ddb.ui.yaml:
  dataDir: ./path/to/data
  port: 3070

For in-memory (no persistence):
  ddb ui --memory

To browse real AWS DynamoDB:
  ddb ui --aws`)
	}

	// Auto-discover schema files
	schemaFiles, err := DiscoverSchemas()
	if err != nil {
		return fmt.Errorf("discovering schemas: %w", err)
	}
	if len(schemaFiles) == 0 {
		return fmt.Errorf(`no schema files found

Generate schema files with:
  //go:generate ddb gen
  go generate ./...

Schema files must contain the header:
  # Generated by ddbgen. DO NOT EDIT.`)
	}

	fmt.Printf("ddb ui: found %d schema file(s)\n", len(schemaFiles))

	schemas, err := ddbui.LoadSchemaFilesRaw(schemaFiles)
	if err != nil {
		return fmt.Errorf("loading schemas: %w", err)
	}

	tableDefs := ddbui.TableDefinitionsFromSchemas(schemas...)

	storeOpts := ddbstore.StoreOptions{
		Path:     dataDir,
		InMemory: memory || dataDir == "",
	}
	store, err := ddbstore.New(storeOpts, tableDefs...)
	if err != nil {
		return fmt.Errorf("creating store: %w", err)
	}
	defer store.Close()

	server, err := ddbui.NewServer(store, serverPort, ddbui.ServerMode{}, schemas...)
	if err != nil {
		return err
	}

	return server.Run()
}

// runUIAWS starts the UI backed by a real AWS DynamoDB client.
func runUIAWS(serverPort int, region, profile, endpoint string) error {
	ctx := context.Background()

	awsOpts := AWSOptions{
		Region:   region,
		Profile:  profile,
		Endpoint: endpoint,
	}

	fmt.Println("ddb ui: connecting to AWS DynamoDB...")

	client, err := createAWSClient(ctx, awsOpts)
	if err != nil {
		return err
	}

	// Try to discover schema files (optional in AWS mode)
	var schemas []schema.Schema
	schemaFiles, _ := DiscoverSchemas()
	if len(schemaFiles) > 0 {
		fmt.Printf("ddb ui: found %d schema file(s)\n", len(schemaFiles))
		schemas, err = ddbui.LoadSchemaFilesRaw(schemaFiles)
		if err != nil {
			return fmt.Errorf("loading schemas: %w", err)
		}
	}

	// Build set of tables already covered by schema files
	existingTables := make(map[string]bool)
	for _, s := range schemas {
		for _, t := range s.Tables {
			existingTables[t.Name] = true
		}
	}

	// Auto-discover remaining tables from AWS
	discovered, err := discoverAWSTables(ctx, client, existingTables)
	if err != nil {
		return fmt.Errorf("discovering AWS tables: %w", err)
	}

	if len(discovered) > 0 {
		fmt.Printf("ddb ui: discovered %d table(s) from AWS\n", len(discovered))
		schemas = append(schemas, schema.Schema{Tables: discovered})
	}

	if len(schemas) == 0 {
		return fmt.Errorf("no tables found (no schema files and no tables in AWS account)")
	}

	// Resolve the effective region for display.
	// The client's Options() includes the resolved region from the config chain.
	displayRegion := region
	if displayRegion == "" {
		displayRegion = client.Options().Region
	}

	// Resolve the AWS account ID and alias (best-effort, non-fatal).
	accountInfo := getAWSAccountInfo(ctx, awsOpts)

	mode := ddbui.ServerMode{
		IsAWS:        true,
		Region:       displayRegion,
		Profile:      profile,
		Endpoint:     endpoint,
		AccountID:    accountInfo.AccountID,
		AccountAlias: accountInfo.Alias,
	}

	server, err := ddbui.NewServer(client, serverPort, mode, schemas...)
	if err != nil {
		return err
	}

	return server.Run()
}
