// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"norm/normddb/expressionparser/ast"
	"norm/normddb/expressionparser/astutil"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Start",
			pos:  position{line: 15, col: 1, offset: 275},
			expr: &actionExpr{
				pos: position{line: 16, col: 5, offset: 285},
				run: (*parser).callonStart1,
				expr: &seqExpr{
					pos: position{line: 16, col: 5, offset: 285},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 16, col: 5, offset: 285},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 16, col: 7, offset: 287},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 16, col: 12, offset: 292},
								name: "OrConditionExpression",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 16, col: 34, offset: 314},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "OrConditionExpression",
			pos:  position{line: 23, col: 1, offset: 473},
			expr: &choiceExpr{
				pos: position{line: 24, col: 5, offset: 499},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 24, col: 5, offset: 499},
						run: (*parser).callonOrConditionExpression2,
						expr: &seqExpr{
							pos: position{line: 24, col: 5, offset: 499},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 24, col: 5, offset: 499},
									label: "x",
									expr: &ruleRefExpr{
										pos:  position{line: 24, col: 7, offset: 501},
										name: "AndConditionExpression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 24, col: 30, offset: 524},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 24, col: 32, offset: 526},
									label: "token",
									expr: &ruleRefExpr{
										pos:  position{line: 24, col: 38, offset: 532},
										name: "OrToken",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 24, col: 46, offset: 540},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 24, col: 48, offset: 542},
									label: "y",
									expr: &ruleRefExpr{
										pos:  position{line: 24, col: 50, offset: 544},
										name: "OrConditionExpression",
									},
								},
							},
						},
					},
					&labeledExpr{
						pos:   position{line: 29, col: 5, offset: 683},
						label: "expr",
						expr: &ruleRefExpr{
							pos:  position{line: 29, col: 10, offset: 688},
							name: "AndConditionExpression",
						},
					},
				},
			},
		},
		{
			name: "AndConditionExpression",
			pos:  position{line: 31, col: 1, offset: 712},
			expr: &choiceExpr{
				pos: position{line: 32, col: 5, offset: 739},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 32, col: 5, offset: 739},
						run: (*parser).callonAndConditionExpression2,
						expr: &seqExpr{
							pos: position{line: 32, col: 5, offset: 739},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 32, col: 5, offset: 739},
									label: "x",
									expr: &ruleRefExpr{
										pos:  position{line: 32, col: 7, offset: 741},
										name: "NotConditionExpression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 32, col: 30, offset: 764},
									name: "_",
								},
								&ruleRefExpr{
									pos:  position{line: 32, col: 32, offset: 766},
									name: "AndToken",
								},
								&ruleRefExpr{
									pos:  position{line: 32, col: 41, offset: 775},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 32, col: 43, offset: 777},
									label: "y",
									expr: &ruleRefExpr{
										pos:  position{line: 32, col: 45, offset: 779},
										name: "AndConditionExpression",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 37, col: 5, offset: 920},
						name: "NotConditionExpression",
					},
				},
			},
		},
		{
			name: "NotConditionExpression",
			pos:  position{line: 39, col: 1, offset: 944},
			expr: &choiceExpr{
				pos: position{line: 40, col: 5, offset: 971},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 40, col: 5, offset: 971},
						run: (*parser).callonNotConditionExpression2,
						expr: &seqExpr{
							pos: position{line: 40, col: 5, offset: 971},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 40, col: 5, offset: 971},
									label: "token",
									expr: &ruleRefExpr{
										pos:  position{line: 40, col: 11, offset: 977},
										name: "NotToken",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 40, col: 20, offset: 986},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 40, col: 22, offset: 988},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 40, col: 27, offset: 993},
										name: "ParensConditionExpression",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 44, col: 5, offset: 1109},
						name: "ParensConditionExpression",
					},
				},
			},
		},
		{
			name: "ParensConditionExpression",
			pos:  position{line: 46, col: 1, offset: 1136},
			expr: &choiceExpr{
				pos: position{line: 47, col: 5, offset: 1166},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 47, col: 5, offset: 1166},
						run: (*parser).callonParensConditionExpression2,
						expr: &seqExpr{
							pos: position{line: 47, col: 5, offset: 1166},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 47, col: 5, offset: 1166},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 47, col: 9, offset: 1170},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 47, col: 11, offset: 1172},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 47, col: 15, offset: 1176},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 47, col: 17, offset: 1178},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 47, col: 22, offset: 1183},
										name: "OrConditionExpression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 47, col: 44, offset: 1205},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 47, col: 46, offset: 1207},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
								&ruleRefExpr{
									pos:  position{line: 47, col: 50, offset: 1211},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 47, col: 52, offset: 1213},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 51, col: 5, offset: 1286},
						run: (*parser).callonParensConditionExpression14,
						expr: &seqExpr{
							pos: position{line: 51, col: 5, offset: 1286},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 51, col: 5, offset: 1286},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 51, col: 9, offset: 1290},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 51, col: 11, offset: 1292},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 51, col: 15, offset: 1296},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 51, col: 17, offset: 1298},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 51, col: 22, offset: 1303},
										name: "ConditionExpression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 51, col: 42, offset: 1323},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 51, col: 44, offset: 1325},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
								&ruleRefExpr{
									pos:  position{line: 51, col: 48, offset: 1329},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 51, col: 50, offset: 1331},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 56, col: 5, offset: 1438},
						run: (*parser).callonParensConditionExpression26,
						expr: &labeledExpr{
							pos:   position{line: 56, col: 5, offset: 1438},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 56, col: 10, offset: 1443},
								name: "ConditionExpression",
							},
						},
					},
					&actionExpr{
						pos: position{line: 60, col: 5, offset: 1532},
						run: (*parser).callonParensConditionExpression29,
						expr: &seqExpr{
							pos: position{line: 60, col: 5, offset: 1532},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 60, col: 5, offset: 1532},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 60, col: 9, offset: 1536},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 60, col: 11, offset: 1538},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 60, col: 16, offset: 1543},
										name: "OrConditionExpression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 60, col: 38, offset: 1565},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 60, col: 40, offset: 1567},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ConditionExpression",
			pos:  position{line: 64, col: 1, offset: 1603},
			expr: &choiceExpr{
				pos: position{line: 65, col: 5, offset: 1627},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 65, col: 5, offset: 1627},
						run: (*parser).callonConditionExpression2,
						expr: &seqExpr{
							pos: position{line: 65, col: 5, offset: 1627},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 65, col: 5, offset: 1627},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 65, col: 10, offset: 1632},
										name: "OperandParens",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 65, col: 24, offset: 1646},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 65, col: 26, offset: 1648},
									label: "comp",
									expr: &ruleRefExpr{
										pos:  position{line: 65, col: 31, offset: 1653},
										name: "Comparator",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 65, col: 42, offset: 1664},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 65, col: 44, offset: 1666},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 65, col: 50, offset: 1672},
										name: "OperandParens",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 70, col: 5, offset: 1832},
						run: (*parser).callonConditionExpression12,
						expr: &seqExpr{
							pos: position{line: 70, col: 5, offset: 1832},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 70, col: 5, offset: 1832},
									label: "val",
									expr: &ruleRefExpr{
										pos:  position{line: 70, col: 9, offset: 1836},
										name: "OperandParens",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 70, col: 23, offset: 1850},
									name: "_",
								},
								&ruleRefExpr{
									pos:  position{line: 70, col: 25, offset: 1852},
									name: "BetweenToken",
								},
								&ruleRefExpr{
									pos:  position{line: 70, col: 38, offset: 1865},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 70, col: 40, offset: 1867},
									label: "low",
									expr: &ruleRefExpr{
										pos:  position{line: 70, col: 44, offset: 1871},
										name: "OperandParens",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 70, col: 58, offset: 1885},
									name: "_",
								},
								&ruleRefExpr{
									pos:  position{line: 70, col: 60, offset: 1887},
									name: "AndToken",
								},
								&ruleRefExpr{
									pos:  position{line: 70, col: 69, offset: 1896},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 70, col: 71, offset: 1898},
									label: "high",
									expr: &ruleRefExpr{
										pos:  position{line: 70, col: 76, offset: 1903},
										name: "OperandParens",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 75, col: 5, offset: 2055},
						run: (*parser).callonConditionExpression26,
						expr: &seqExpr{
							pos: position{line: 75, col: 5, offset: 2055},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 75, col: 5, offset: 2055},
									label: "val",
									expr: &ruleRefExpr{
										pos:  position{line: 75, col: 9, offset: 2059},
										name: "OperandParens",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 75, col: 23, offset: 2073},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 75, col: 25, offset: 2075},
									label: "token",
									expr: &ruleRefExpr{
										pos:  position{line: 75, col: 31, offset: 2081},
										name: "InToken",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 75, col: 39, offset: 2089},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 75, col: 41, offset: 2091},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 75, col: 45, offset: 2095},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 75, col: 47, offset: 2097},
									label: "container",
									expr: &ruleRefExpr{
										pos:  position{line: 75, col: 57, offset: 2107},
										name: "FunctionArgumentList",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 75, col: 78, offset: 2128},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 75, col: 80, offset: 2130},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&labeledExpr{
						pos:   position{line: 79, col: 5, offset: 2248},
						label: "f",
						expr: &ruleRefExpr{
							pos:  position{line: 79, col: 7, offset: 2250},
							name: "Function",
						},
					},
				},
			},
		},
		{
			name: "Comparator",
			pos:  position{line: 81, col: 1, offset: 2260},
			expr: &choiceExpr{
				pos: position{line: 82, col: 5, offset: 2275},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 82, col: 5, offset: 2275},
						val:        ">=",
						ignoreCase: false,
						want:       "\">=\"",
					},
					&litMatcher{
						pos:        position{line: 83, col: 5, offset: 2284},
						val:        "<=",
						ignoreCase: false,
						want:       "\"<=\"",
					},
					&litMatcher{
						pos:        position{line: 84, col: 5, offset: 2293},
						val:        "<>",
						ignoreCase: false,
						want:       "\"<>\"",
					},
					&litMatcher{
						pos:        position{line: 85, col: 5, offset: 2302},
						val:        "=",
						ignoreCase: false,
						want:       "\"=\"",
					},
					&litMatcher{
						pos:        position{line: 86, col: 5, offset: 2310},
						val:        "<",
						ignoreCase: false,
						want:       "\"<\"",
					},
					&litMatcher{
						pos:        position{line: 87, col: 5, offset: 2318},
						val:        ">",
						ignoreCase: false,
						want:       "\">\"",
					},
				},
			},
		},
		{
			name: "OperandParens",
			pos:  position{line: 89, col: 1, offset: 2323},
			expr: &choiceExpr{
				pos: position{line: 90, col: 5, offset: 2341},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 90, col: 5, offset: 2341},
						run: (*parser).callonOperandParens2,
						expr: &seqExpr{
							pos: position{line: 90, col: 5, offset: 2341},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 90, col: 5, offset: 2341},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 90, col: 9, offset: 2345},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 90, col: 11, offset: 2347},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 90, col: 15, offset: 2351},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 90, col: 17, offset: 2353},
									label: "op",
									expr: &ruleRefExpr{
										pos:  position{line: 90, col: 20, offset: 2356},
										name: "Operand",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 90, col: 28, offset: 2364},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 90, col: 30, offset: 2366},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
								&ruleRefExpr{
									pos:  position{line: 90, col: 34, offset: 2370},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 90, col: 36, offset: 2372},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 94, col: 5, offset: 2441},
						run: (*parser).callonOperandParens14,
						expr: &seqExpr{
							pos: position{line: 94, col: 5, offset: 2441},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 94, col: 5, offset: 2441},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 94, col: 9, offset: 2445},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 94, col: 11, offset: 2447},
									label: "op",
									expr: &ruleRefExpr{
										pos:  position{line: 94, col: 14, offset: 2450},
										name: "Operand",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 94, col: 22, offset: 2458},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 94, col: 24, offset: 2460},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 97, col: 5, offset: 2497},
						name: "Operand",
					},
				},
			},
		},
		{
			name: "Operand",
			pos:  position{line: 99, col: 1, offset: 2506},
			expr: &choiceExpr{
				pos: position{line: 100, col: 5, offset: 2518},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 100, col: 5, offset: 2518},
						name: "Function",
					},
					&ruleRefExpr{
						pos:  position{line: 101, col: 5, offset: 2531},
						name: "ExpressionAttributeValue",
					},
					&labeledExpr{
						pos:   position{line: 102, col: 5, offset: 2560},
						label: "path",
						expr: &ruleRefExpr{
							pos:  position{line: 102, col: 10, offset: 2565},
							name: "PathExpression",
						},
					},
				},
			},
		},
		{
			name: "Function",
			pos:  position{line: 104, col: 1, offset: 2582},
			expr: &actionExpr{
				pos: position{line: 105, col: 5, offset: 2595},
				run: (*parser).callonFunction1,
				expr: &seqExpr{
					pos: position{line: 105, col: 5, offset: 2595},
					exprs: []any{
						&notExpr{
							pos: position{line: 105, col: 5, offset: 2595},
							expr: &ruleRefExpr{
								pos:  position{line: 105, col: 6, offset: 2596},
								name: "ReservedWord",
							},
						},
						&labeledExpr{
							pos:   position{line: 105, col: 19, offset: 2609},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 105, col: 24, offset: 2614},
								name: "IdentifierStart",
							},
						},
						&labeledExpr{
							pos:   position{line: 105, col: 40, offset: 2630},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 105, col: 45, offset: 2635},
								expr: &ruleRefExpr{
									pos:  position{line: 105, col: 45, offset: 2635},
									name: "IdentifierPart",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 105, col: 61, offset: 2651},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 105, col: 63, offset: 2653},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 105, col: 67, offset: 2657},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 105, col: 69, offset: 2659},
							label: "args",
							expr: &ruleRefExpr{
								pos:  position{line: 105, col: 74, offset: 2664},
								name: "FunctionArgumentList",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 105, col: 95, offset: 2685},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 105, col: 97, offset: 2687},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "FunctionArgumentList",
			pos:  position{line: 112, col: 1, offset: 2886},
			expr: &actionExpr{
				pos: position{line: 113, col: 5, offset: 2911},
				run: (*parser).callonFunctionArgumentList1,
				expr: &seqExpr{
					pos: position{line: 113, col: 5, offset: 2911},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 113, col: 5, offset: 2911},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 113, col: 10, offset: 2916},
								name: "OperandParens",
							},
						},
						&labeledExpr{
							pos:   position{line: 113, col: 24, offset: 2930},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 113, col: 29, offset: 2935},
								expr: &actionExpr{
									pos: position{line: 113, col: 30, offset: 2936},
									run: (*parser).callonFunctionArgumentList7,
									expr: &seqExpr{
										pos: position{line: 113, col: 30, offset: 2936},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 113, col: 30, offset: 2936},
												name: "_",
											},
											&litMatcher{
												pos:        position{line: 113, col: 32, offset: 2938},
												val:        ",",
												ignoreCase: false,
												want:       "\",\"",
											},
											&ruleRefExpr{
												pos:  position{line: 113, col: 36, offset: 2942},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 113, col: 38, offset: 2944},
												label: "expr",
												expr: &ruleRefExpr{
													pos:  position{line: 113, col: 43, offset: 2949},
													name: "OperandParens",
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ExpressionAttributeName",
			pos:  position{line: 117, col: 1, offset: 3046},
			expr: &actionExpr{
				pos: position{line: 118, col: 5, offset: 3074},
				run: (*parser).callonExpressionAttributeName1,
				expr: &seqExpr{
					pos: position{line: 118, col: 5, offset: 3074},
					exprs: []any{
						&notExpr{
							pos: position{line: 118, col: 5, offset: 3074},
							expr: &ruleRefExpr{
								pos:  position{line: 118, col: 6, offset: 3075},
								name: "ReservedWord",
							},
						},
						&labeledExpr{
							pos:   position{line: 118, col: 19, offset: 3088},
							label: "head",
							expr: &litMatcher{
								pos:        position{line: 118, col: 24, offset: 3093},
								val:        "#",
								ignoreCase: false,
								want:       "\"#\"",
							},
						},
						&labeledExpr{
							pos:   position{line: 118, col: 28, offset: 3097},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 118, col: 33, offset: 3102},
								expr: &ruleRefExpr{
									pos:  position{line: 118, col: 33, offset: 3102},
									name: "IdentifierPart",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ExpressionAttributeValue",
			pos:  position{line: 122, col: 1, offset: 3212},
			expr: &actionExpr{
				pos: position{line: 123, col: 5, offset: 3241},
				run: (*parser).callonExpressionAttributeValue1,
				expr: &seqExpr{
					pos: position{line: 123, col: 5, offset: 3241},
					exprs: []any{
						&notExpr{
							pos: position{line: 123, col: 5, offset: 3241},
							expr: &ruleRefExpr{
								pos:  position{line: 123, col: 6, offset: 3242},
								name: "ReservedWord",
							},
						},
						&labeledExpr{
							pos:   position{line: 123, col: 19, offset: 3255},
							label: "head",
							expr: &litMatcher{
								pos:        position{line: 123, col: 24, offset: 3260},
								val:        ":",
								ignoreCase: false,
								want:       "\":\"",
							},
						},
						&labeledExpr{
							pos:   position{line: 123, col: 28, offset: 3264},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 123, col: 33, offset: 3269},
								expr: &ruleRefExpr{
									pos:  position{line: 123, col: 33, offset: 3269},
									name: "IdentifierPart",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "PathExpression",
			pos:  position{line: 128, col: 1, offset: 3425},
			expr: &actionExpr{
				pos: position{line: 129, col: 5, offset: 3444},
				run: (*parser).callonPathExpression1,
				expr: &seqExpr{
					pos: position{line: 129, col: 5, offset: 3444},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 129, col: 5, offset: 3444},
							label: "head",
							expr: &ruleRefExpr{
								pos:  position{line: 129, col: 10, offset: 3449},
								name: "GroupedPathExpression",
							},
						},
						&labeledExpr{
							pos:   position{line: 129, col: 32, offset: 3471},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 129, col: 37, offset: 3476},
								expr: &choiceExpr{
									pos: position{line: 130, col: 7, offset: 3484},
									alternatives: []any{
										&actionExpr{
											pos: position{line: 130, col: 7, offset: 3484},
											run: (*parser).callonPathExpression8,
											expr: &seqExpr{
												pos: position{line: 130, col: 7, offset: 3484},
												exprs: []any{
													&ruleRefExpr{
														pos:  position{line: 130, col: 7, offset: 3484},
														name: "_",
													},
													&litMatcher{
														pos:        position{line: 130, col: 9, offset: 3486},
														val:        "[",
														ignoreCase: false,
														want:       "\"[\"",
													},
													&ruleRefExpr{
														pos:  position{line: 130, col: 13, offset: 3490},
														name: "_",
													},
													&labeledExpr{
														pos:   position{line: 130, col: 15, offset: 3492},
														label: "ix",
														expr: &oneOrMoreExpr{
															pos: position{line: 130, col: 18, offset: 3495},
															expr: &charClassMatcher{
																pos:        position{line: 130, col: 18, offset: 3495},
																val:        "[0-9]",
																ranges:     []rune{'0', '9'},
																ignoreCase: false,
																inverted:   false,
															},
														},
													},
													&ruleRefExpr{
														pos:  position{line: 130, col: 25, offset: 3502},
														name: "_",
													},
													&litMatcher{
														pos:        position{line: 130, col: 27, offset: 3504},
														val:        "]",
														ignoreCase: false,
														want:       "\"]\"",
													},
												},
											},
										},
										&actionExpr{
											pos: position{line: 133, col: 7, offset: 3575},
											run: (*parser).callonPathExpression18,
											expr: &seqExpr{
												pos: position{line: 133, col: 7, offset: 3575},
												exprs: []any{
													&ruleRefExpr{
														pos:  position{line: 133, col: 7, offset: 3575},
														name: "_",
													},
													&litMatcher{
														pos:        position{line: 133, col: 9, offset: 3577},
														val:        ".",
														ignoreCase: false,
														want:       "\".\"",
													},
													&ruleRefExpr{
														pos:  position{line: 133, col: 13, offset: 3581},
														name: "_",
													},
													&labeledExpr{
														pos:   position{line: 133, col: 15, offset: 3583},
														label: "prop",
														expr: &ruleRefExpr{
															pos:  position{line: 133, col: 20, offset: 3588},
															name: "Identifier",
														},
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "GroupedPathExpression",
			pos:  position{line: 140, col: 1, offset: 3715},
			expr: &choiceExpr{
				pos: position{line: 141, col: 5, offset: 3741},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 141, col: 5, offset: 3741},
						name: "Identifier",
					},
					&actionExpr{
						pos: position{line: 142, col: 5, offset: 3756},
						run: (*parser).callonGroupedPathExpression3,
						expr: &seqExpr{
							pos: position{line: 142, col: 5, offset: 3756},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 142, col: 5, offset: 3756},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 142, col: 9, offset: 3760},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 142, col: 11, offset: 3762},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 142, col: 15, offset: 3766},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 142, col: 17, offset: 3768},
									label: "path",
									expr: &ruleRefExpr{
										pos:  position{line: 142, col: 22, offset: 3773},
										name: "PathExpression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 142, col: 37, offset: 3788},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 142, col: 39, offset: 3790},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
								&ruleRefExpr{
									pos:  position{line: 142, col: 43, offset: 3794},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 142, col: 45, offset: 3796},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 146, col: 5, offset: 3867},
						run: (*parser).callonGroupedPathExpression15,
						expr: &seqExpr{
							pos: position{line: 146, col: 5, offset: 3867},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 146, col: 5, offset: 3867},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 146, col: 9, offset: 3871},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 146, col: 11, offset: 3873},
									label: "path",
									expr: &ruleRefExpr{
										pos:  position{line: 146, col: 16, offset: 3878},
										name: "PathExpression",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 146, col: 31, offset: 3893},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 146, col: 33, offset: 3895},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 150, col: 1, offset: 3931},
			expr: &choiceExpr{
				pos: position{line: 151, col: 5, offset: 3946},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 151, col: 5, offset: 3946},
						run: (*parser).callonIdentifier2,
						expr: &seqExpr{
							pos: position{line: 151, col: 5, offset: 3946},
							exprs: []any{
								&notExpr{
									pos: position{line: 151, col: 5, offset: 3946},
									expr: &ruleRefExpr{
										pos:  position{line: 151, col: 6, offset: 3947},
										name: "ReservedWord",
									},
								},
								&labeledExpr{
									pos:   position{line: 151, col: 19, offset: 3960},
									label: "head",
									expr: &ruleRefExpr{
										pos:  position{line: 151, col: 24, offset: 3965},
										name: "IdentifierStart",
									},
								},
								&labeledExpr{
									pos:   position{line: 151, col: 40, offset: 3981},
									label: "tail",
									expr: &zeroOrMoreExpr{
										pos: position{line: 151, col: 45, offset: 3986},
										expr: &ruleRefExpr{
											pos:  position{line: 151, col: 45, offset: 3986},
											name: "IdentifierPart",
										},
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 154, col: 5, offset: 4067},
						name: "ExpressionAttributeName",
					},
				},
			},
		},
		{
			name: "IdentifierStart",
			pos:  position{line: 156, col: 1, offset: 4092},
			expr: &choiceExpr{
				pos: position{line: 157, col: 5, offset: 4112},
				alternatives: []any{
					&charClassMatcher{
						pos:        position{line: 157, col: 5, offset: 4112},
						val:        "[a-zA-Z]",
						ranges:     []rune{'a', 'z', 'A', 'Z'},
						ignoreCase: false,
						inverted:   false,
					},
					&litMatcher{
						pos:        position{line: 158, col: 5, offset: 4125},
						val:        "_",
						ignoreCase: false,
						want:       "\"_\"",
					},
				},
			},
		},
		{
			name: "IdentifierPart",
			pos:  position{line: 160, col: 1, offset: 4130},
			expr: &choiceExpr{
				pos: position{line: 161, col: 5, offset: 4149},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 161, col: 5, offset: 4149},
						name: "IdentifierStart",
					},
					&charClassMatcher{
						pos:        position{line: 162, col: 5, offset: 4169},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "AttributePart",
			pos:  position{line: 164, col: 1, offset: 4176},
			expr: &choiceExpr{
				pos: position{line: 165, col: 5, offset: 4194},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 165, col: 5, offset: 4194},
						name: "IdentifierPart",
					},
					&litMatcher{
						pos:        position{line: 166, col: 5, offset: 4213},
						val:        "#",
						ignoreCase: false,
						want:       "\"#\"",
					},
					&litMatcher{
						pos:        position{line: 167, col: 5, offset: 4221},
						val:        ":",
						ignoreCase: false,
						want:       "\":\"",
					},
				},
			},
		},
		{
			name: "ReservedWord",
			pos:  position{line: 169, col: 1, offset: 4226},
			expr: &choiceExpr{
				pos: position{line: 170, col: 5, offset: 4243},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 170, col: 5, offset: 4243},
						name: "BetweenToken",
					},
					&ruleRefExpr{
						pos:  position{line: 171, col: 5, offset: 4260},
						name: "InToken",
					},
					&ruleRefExpr{
						pos:  position{line: 172, col: 5, offset: 4272},
						name: "AndToken",
					},
					&ruleRefExpr{
						pos:  position{line: 173, col: 5, offset: 4285},
						name: "OrToken",
					},
					&ruleRefExpr{
						pos:  position{line: 174, col: 5, offset: 4297},
						name: "NotToken",
					},
				},
			},
		},
		{
			name: "BetweenToken",
			pos:  position{line: 176, col: 1, offset: 4307},
			expr: &seqExpr{
				pos: position{line: 176, col: 16, offset: 4322},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 176, col: 16, offset: 4322},
						val:        "between",
						ignoreCase: true,
						want:       "\"BETWEEN\"i",
					},
					&notExpr{
						pos: position{line: 176, col: 27, offset: 4333},
						expr: &ruleRefExpr{
							pos:  position{line: 176, col: 28, offset: 4334},
							name: "AttributePart",
						},
					},
				},
			},
		},
		{
			name: "InToken",
			pos:  position{line: 177, col: 1, offset: 4348},
			expr: &seqExpr{
				pos: position{line: 177, col: 11, offset: 4358},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 177, col: 11, offset: 4358},
						val:        "in",
						ignoreCase: true,
						want:       "\"IN\"i",
					},
					&notExpr{
						pos: position{line: 177, col: 17, offset: 4364},
						expr: &ruleRefExpr{
							pos:  position{line: 177, col: 18, offset: 4365},
							name: "AttributePart",
						},
					},
				},
			},
		},
		{
			name: "AndToken",
			pos:  position{line: 178, col: 1, offset: 4379},
			expr: &seqExpr{
				pos: position{line: 178, col: 12, offset: 4390},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 178, col: 12, offset: 4390},
						val:        "and",
						ignoreCase: true,
						want:       "\"AND\"i",
					},
					&notExpr{
						pos: position{line: 178, col: 19, offset: 4397},
						expr: &ruleRefExpr{
							pos:  position{line: 178, col: 20, offset: 4398},
							name: "AttributePart",
						},
					},
				},
			},
		},
		{
			name: "OrToken",
			pos:  position{line: 179, col: 1, offset: 4412},
			expr: &seqExpr{
				pos: position{line: 179, col: 11, offset: 4422},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 179, col: 11, offset: 4422},
						val:        "or",
						ignoreCase: true,
						want:       "\"OR\"i",
					},
					&notExpr{
						pos: position{line: 179, col: 17, offset: 4428},
						expr: &ruleRefExpr{
							pos:  position{line: 179, col: 18, offset: 4429},
							name: "AttributePart",
						},
					},
				},
			},
		},
		{
			name: "NotToken",
			pos:  position{line: 180, col: 1, offset: 4443},
			expr: &seqExpr{
				pos: position{line: 180, col: 12, offset: 4454},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 180, col: 12, offset: 4454},
						val:        "not",
						ignoreCase: true,
						want:       "\"NOT\"i",
					},
					&notExpr{
						pos: position{line: 180, col: 19, offset: 4461},
						expr: &ruleRefExpr{
							pos:  position{line: 180, col: 20, offset: 4462},
							name: "AttributePart",
						},
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 182, col: 1, offset: 4477},
			expr: &zeroOrMoreExpr{
				pos: position{line: 183, col: 5, offset: 4496},
				expr: &charClassMatcher{
					pos:        position{line: 183, col: 5, offset: 4496},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
	},
}

func (c *current) onStart1(expr any) (any, error) {

	// c.checkMisusedSize(expr)
	//todo { nestedPaths: nestedPaths, pathHeads: pathHeads }
	// c.checkErrors()
	return expr, nil

}

func (p *parser) callonStart1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStart1(stack["expr"])
}

func (c *current) onOrConditionExpression2(x, token, y any) (any, error) {
	// c.checkMisusedSize(x)
	// c.checkMisusedSize(y)
	return ast.NewOrCondition(x, y), nil

}

func (p *parser) callonOrConditionExpression2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrConditionExpression2(stack["x"], stack["token"], stack["y"])
}

func (c *current) onAndConditionExpression2(x, y any) (any, error) {
	// c.checkMisusedSize(x)
	// c.checkMisusedSize(y)
	return ast.NewAndCondition(x, y), nil

}

func (p *parser) callonAndConditionExpression2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndConditionExpression2(stack["x"], stack["y"])
}

func (c *current) onNotConditionExpression2(token, expr any) (any, error) {
	// c.checkMisusedSize(expr)
	return ast.NewNotCondition(expr), nil

}

func (p *parser) callonNotConditionExpression2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNotConditionExpression2(stack["token"], stack["expr"])
}

func (c *current) onParensConditionExpression2(expr any) (any, error) {
	// c.redundantParensError()
	return expr, nil

}

func (p *parser) callonParensConditionExpression2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParensConditionExpression2(stack["expr"])
}

func (c *current) onParensConditionExpression14(expr any) (any, error) {
	// c.redundantParensError()
	// c.checkConditionErrors()
	return expr, nil

}

func (p *parser) callonParensConditionExpression14() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParensConditionExpression14(stack["expr"])
}

func (c *current) onParensConditionExpression26(expr any) (any, error) {
	// c.checkConditionErrors()
	return expr, nil

}

func (p *parser) callonParensConditionExpression26() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParensConditionExpression26(stack["expr"])
}

func (c *current) onParensConditionExpression29(expr any) (any, error) {
	return expr, nil

}

func (p *parser) callonParensConditionExpression29() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParensConditionExpression29(stack["expr"])
}

func (c *current) onConditionExpression2(left, comp, right any) (any, error) {
	// c.checkMisusedFunction([x, y])
	// c.checkDistinct(comp, [x, y])
	return ast.NewComparison(comp, left, right), nil

}

func (p *parser) callonConditionExpression2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConditionExpression2(stack["left"], stack["comp"], stack["right"])
}

func (c *current) onConditionExpression12(val, low, high any) (any, error) {
	// checkMisusedFunction([x, y, z])
	// checkBetweenArgs(y, z)
	return ast.NewBetweenExpr(val, low, high), nil

}

func (p *parser) callonConditionExpression12() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConditionExpression12(stack["val"], stack["low"], stack["high"])
}

func (c *current) onConditionExpression26(val, token, container any) (any, error) {
	// checkMisusedFunction([x].concat(args))
	return ast.NewContainsExpr(container, val), nil

}

func (p *parser) callonConditionExpression26() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConditionExpression26(stack["val"], stack["token"], stack["container"])
}

func (c *current) onOperandParens2(op any) (any, error) {
	// redundantParensError()
	return op, nil

}

func (p *parser) callonOperandParens2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOperandParens2(stack["op"])
}

func (c *current) onOperandParens14(op any) (any, error) {
	return op, nil

}

func (p *parser) callonOperandParens14() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOperandParens14(stack["op"])
}

func (c *current) onFunction1(head, tail, args any) (any, error) {
	// checkMisusedFunction(args)
	name := astutil.HeadTailString(head, tail)
	// attrType := checkFunction(name, args)
	return ast.NewFunctionCallExpr(name, args), nil

}

func (p *parser) callonFunction1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunction1(stack["head"], stack["tail"], stack["args"])
}

func (c *current) onFunctionArgumentList7(expr any) (any, error) {
	return expr, nil
}

func (p *parser) callonFunctionArgumentList7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionArgumentList7(stack["expr"])
}

func (c *current) onFunctionArgumentList1(head, tail any) (any, error) {
	return astutil.HeadTailList(head, tail), nil

}

func (p *parser) callonFunctionArgumentList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunctionArgumentList1(stack["head"], stack["tail"])
}

func (c *current) onExpressionAttributeName1(head, tail any) (any, error) {
	return ast.NewExpressionAttributeName(astutil.HeadTailString(head, tail)), nil

}

func (p *parser) callonExpressionAttributeName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpressionAttributeName1(stack["head"], stack["tail"])
}

func (c *current) onExpressionAttributeValue1(head, tail any) (any, error) {
	// resolveAttrVal(head + tail.join(''))
	return ast.NewExpressionAttributeValue(astutil.HeadTailString(head, tail)), nil

}

func (p *parser) callonExpressionAttributeValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpressionAttributeValue1(stack["head"], stack["tail"])
}

func (c *current) onPathExpression8(ix any) (any, error) {
	return astutil.Atoi(astutil.Join(ix)), nil

}

func (p *parser) callonPathExpression8() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPathExpression8(stack["ix"])
}

func (c *current) onPathExpression18(prop any) (any, error) {
	return string(c.text), nil

}

func (p *parser) callonPathExpression18() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPathExpression18(stack["prop"])
}

func (c *current) onPathExpression1(head, tail any) (any, error) {
	return ast.NewAttributePathExpr(head, tail), nil

}

func (p *parser) callonPathExpression1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPathExpression1(stack["head"], stack["tail"])
}

func (c *current) onGroupedPathExpression3(path any) (any, error) {
	// redundantParensError()
	return path, nil

}

func (p *parser) callonGroupedPathExpression3() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGroupedPathExpression3(stack["path"])
}

func (c *current) onGroupedPathExpression15(path any) (any, error) {
	return path, nil

}

func (p *parser) callonGroupedPathExpression15() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGroupedPathExpression15(stack["path"])
}

func (c *current) onIdentifier2(head, tail any) (any, error) {
	return astutil.HeadTailString(head, tail), nil

}

func (p *parser) callonIdentifier2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier2(stack["head"], stack["tail"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
