// Code generated by ddbgen. DO NOT EDIT.

package example

import (
	"fmt"
	"github.com/acksell/bezos/dynamodb/ddbsdk"
	"github.com/acksell/bezos/dynamodb/index"
	"github.com/acksell/bezos/dynamodb/table"
)

// =============================================================================
// User Index Wrapper
// =============================================================================

// UserIndexUtil wraps the PrimaryIndex with strongly-typed methods.
type UserIndexUtil struct {
	*index.PrimaryIndex[User]
}

// UserIndex is the typed wrapper for User operations.
var UserIndex = UserIndexUtil{PrimaryIndex: &userIndex}

// PrimaryKey creates a strongly-typed primary key from explicit parameters.
func (idx UserIndexUtil) PrimaryKey(id string) table.PrimaryKey {
	return table.PrimaryKey{
		Definition: idx.Table.KeyDefinitions,
		Values: table.PrimaryKeyValues{
			PartitionKey: fmt.Sprintf("USER#%s", id),
			SortKey:      "PROFILE",
		},
	}
}

// PrimaryKeyFrom extracts the primary key from a User entity.
func (idx UserIndexUtil) PrimaryKeyFrom(e *User) table.PrimaryKey {
	return table.PrimaryKey{
		Definition: idx.Table.KeyDefinitions,
		Values: table.PrimaryKeyValues{
			PartitionKey: fmt.Sprintf("USER#%s", e.UserID),
			SortKey:      "PROFILE",
		},
	}
}

// GSIKeysFrom extracts all GSI keys from a User entity.
func (idx UserIndexUtil) GSIKeysFrom(e *User) []table.PrimaryKey {
	return []table.PrimaryKey{
		{
			Definition: idx.Secondary[0].KeyDefinition(),
			Values: table.PrimaryKeyValues{
				PartitionKey: fmt.Sprintf("EMAIL#%s", e.Email),
				SortKey:      fmt.Sprintf("USER#%s", e.UserID),
			},
		},
	}
}

// UnsafePut creates a Put operation without optimistic locking.
func (idx UserIndexUtil) UnsafePut(e *User) *ddbsdk.Put {
	return ddbsdk.NewUnsafePut(idx.Table, idx.PrimaryKeyFrom(e), e).WithGSIKeys(idx.GSIKeysFrom(e)...)
}

// SafePut creates a Put operation with optimistic locking.
func (idx UserIndexUtil) SafePut(e *User) *ddbsdk.PutWithCondition {
	return ddbsdk.NewSafePut(idx.Table, idx.PrimaryKeyFrom(e), e).WithGSIKeys(idx.GSIKeysFrom(e)...)
}

// Delete creates a Delete operation.
func (idx UserIndexUtil) Delete(id string) *ddbsdk.Delete {
	return ddbsdk.NewDelete(idx.Table, idx.PrimaryKey(id))
}

// UnsafeUpdate creates an Update operation without optimistic locking.
func (idx UserIndexUtil) UnsafeUpdate(id string) *ddbsdk.UnsafeUpdate {
	return ddbsdk.NewUnsafeUpdate(idx.Table, idx.PrimaryKey(id))
}

// ByEmailKey creates a key for querying the ByEmail GSI.
func (idx UserIndexUtil) ByEmailKey(email string, id string) table.PrimaryKey {
	return table.PrimaryKey{
		Definition: idx.Secondary[0].KeyDefinition(),
		Values: table.PrimaryKeyValues{
			PartitionKey: fmt.Sprintf("EMAIL#%s", email),
			SortKey:      fmt.Sprintf("USER#%s", id),
		},
	}
}

// =============================================================================
// Order Index Wrapper
// =============================================================================

// OrderIndexUtil wraps the PrimaryIndex with strongly-typed methods.
type OrderIndexUtil struct {
	*index.PrimaryIndex[Order]
}

// OrderIndex is the typed wrapper for Order operations.
var OrderIndex = OrderIndexUtil{PrimaryIndex: &orderIndex}

// PrimaryKey creates a strongly-typed primary key from explicit parameters.
func (idx OrderIndexUtil) PrimaryKey(tenantID string, orderID string) table.PrimaryKey {
	return table.PrimaryKey{
		Definition: idx.Table.KeyDefinitions,
		Values: table.PrimaryKeyValues{
			PartitionKey: fmt.Sprintf("TENANT#%s", tenantID),
			SortKey:      fmt.Sprintf("ORDER#%s", orderID),
		},
	}
}

// PrimaryKeyFrom extracts the primary key from a Order entity.
func (idx OrderIndexUtil) PrimaryKeyFrom(e *Order) table.PrimaryKey {
	return table.PrimaryKey{
		Definition: idx.Table.KeyDefinitions,
		Values: table.PrimaryKeyValues{
			PartitionKey: fmt.Sprintf("TENANT#%s", e.TenantID),
			SortKey:      fmt.Sprintf("ORDER#%s", e.OrderID),
		},
	}
}

// UnsafePut creates a Put operation without optimistic locking.
func (idx OrderIndexUtil) UnsafePut(e *Order) *ddbsdk.Put {
	return ddbsdk.NewUnsafePut(idx.Table, idx.PrimaryKeyFrom(e), e)
}

// Delete creates a Delete operation.
func (idx OrderIndexUtil) Delete(tenantID string, orderID string) *ddbsdk.Delete {
	return ddbsdk.NewDelete(idx.Table, idx.PrimaryKey(tenantID, orderID))
}

// UnsafeUpdate creates an Update operation without optimistic locking.
func (idx OrderIndexUtil) UnsafeUpdate(tenantID string, orderID string) *ddbsdk.UnsafeUpdate {
	return ddbsdk.NewUnsafeUpdate(idx.Table, idx.PrimaryKey(tenantID, orderID))
}
