// Code generated by pigeon; DO NOT EDIT.

package keyconditions

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"bezos/dynamodb/ddbstore/expressions/astutil"
	"bezos/dynamodb/ddbstore/expressions/keyconditions/ast"
)

func (c *current) paramsFromStore() *keyConditionParserParams {
	v, found := c.globalStore[globalStoreParamsKey]
	if !found {
		panic("no key condition parameters found in parser")
	}
	params, ok := v.(*keyConditionParserParams)
	if !ok {
		panic(fmt.Sprintf("got params type %T, want %T", v, params))
	}
	return params
}

func (c *current) resolveAmbiguousKeyCondition(left, right any) (*ast.KeyCondition, error) {
	// Need to disambiguate between PK and SK if they are both using
	// the "=" operation.
	// Use global store to fetch table key information
	l := astutil.CastTo[*rawEqualCondition](left)
	r := astutil.CastTo[*rawEqualCondition](right)
	intermediary := &ambiguousKeyCondition{l, r}
	return intermediary.Disambiguate(c.paramsFromStore())
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Start",
			pos:  position{line: 38, col: 1, offset: 1196},
			expr: &actionExpr{
				pos: position{line: 39, col: 5, offset: 1206},
				run: (*parser).callonStart1,
				expr: &seqExpr{
					pos: position{line: 39, col: 5, offset: 1206},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 39, col: 5, offset: 1206},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 39, col: 7, offset: 1208},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 39, col: 12, offset: 1213},
								name: "KeyConditionExpression",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 39, col: 35, offset: 1236},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "KeyConditionExpression",
			pos:  position{line: 43, col: 1, offset: 1274},
			expr: &choiceExpr{
				pos: position{line: 44, col: 5, offset: 1301},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 44, col: 5, offset: 1301},
						run: (*parser).callonKeyConditionExpression2,
						expr: &seqExpr{
							pos: position{line: 44, col: 5, offset: 1301},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 44, col: 5, offset: 1301},
									label: "pk",
									expr: &ruleRefExpr{
										pos:  position{line: 44, col: 8, offset: 1304},
										name: "PKCondition",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 44, col: 20, offset: 1316},
									name: "_",
								},
								&ruleRefExpr{
									pos:  position{line: 44, col: 22, offset: 1318},
									name: "AndToken",
								},
								&ruleRefExpr{
									pos:  position{line: 44, col: 31, offset: 1327},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 44, col: 33, offset: 1329},
									label: "sk",
									expr: &ruleRefExpr{
										pos:  position{line: 44, col: 36, offset: 1332},
										name: "SKRangeCondition",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 47, col: 5, offset: 1424},
						run: (*parser).callonKeyConditionExpression11,
						expr: &seqExpr{
							pos: position{line: 47, col: 5, offset: 1424},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 47, col: 5, offset: 1424},
									label: "sk",
									expr: &ruleRefExpr{
										pos:  position{line: 47, col: 8, offset: 1427},
										name: "SKRangeCondition",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 47, col: 25, offset: 1444},
									name: "_",
								},
								&ruleRefExpr{
									pos:  position{line: 47, col: 27, offset: 1446},
									name: "AndToken",
								},
								&ruleRefExpr{
									pos:  position{line: 47, col: 36, offset: 1455},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 47, col: 38, offset: 1457},
									label: "pk",
									expr: &ruleRefExpr{
										pos:  position{line: 47, col: 41, offset: 1460},
										name: "PKCondition",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 50, col: 5, offset: 1547},
						run: (*parser).callonKeyConditionExpression20,
						expr: &seqExpr{
							pos: position{line: 50, col: 5, offset: 1547},
							exprs: []any{
								&labeledExpr{
									pos:   position{line: 50, col: 5, offset: 1547},
									label: "left",
									expr: &ruleRefExpr{
										pos:  position{line: 50, col: 10, offset: 1552},
										name: "EqualsCondition",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 50, col: 26, offset: 1568},
									name: "_",
								},
								&ruleRefExpr{
									pos:  position{line: 50, col: 28, offset: 1570},
									name: "AndToken",
								},
								&ruleRefExpr{
									pos:  position{line: 50, col: 37, offset: 1579},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 50, col: 39, offset: 1581},
									label: "right",
									expr: &ruleRefExpr{
										pos:  position{line: 50, col: 45, offset: 1587},
										name: "EqualsCondition",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 53, col: 5, offset: 1680},
						run: (*parser).callonKeyConditionExpression29,
						expr: &labeledExpr{
							pos:   position{line: 53, col: 5, offset: 1680},
							label: "pk",
							expr: &ruleRefExpr{
								pos:  position{line: 53, col: 8, offset: 1683},
								name: "PKCondition",
							},
						},
					},
				},
			},
		},
		{
			name: "PKCondition",
			pos:  position{line: 57, col: 1, offset: 1821},
			expr: &actionExpr{
				pos: position{line: 58, col: 5, offset: 1837},
				run: (*parser).callonPKCondition1,
				expr: &labeledExpr{
					pos:   position{line: 58, col: 5, offset: 1837},
					label: "eq",
					expr: &ruleRefExpr{
						pos:  position{line: 58, col: 8, offset: 1840},
						name: "EqualsCondition",
					},
				},
			},
		},
		{
			name: "EqualsCondition",
			pos:  position{line: 63, col: 1, offset: 1982},
			expr: &choiceExpr{
				pos: position{line: 64, col: 5, offset: 2002},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 64, col: 5, offset: 2002},
						run: (*parser).callonEqualsCondition2,
						expr: &seqExpr{
							pos: position{line: 64, col: 5, offset: 2002},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 64, col: 5, offset: 2002},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 64, col: 9, offset: 2006},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 64, col: 11, offset: 2008},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 64, col: 15, offset: 2012},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 64, col: 17, offset: 2014},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 64, col: 22, offset: 2019},
										name: "EqualsConditionNoParens",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 64, col: 46, offset: 2043},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 64, col: 48, offset: 2045},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
								&ruleRefExpr{
									pos:  position{line: 64, col: 52, offset: 2049},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 64, col: 54, offset: 2051},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 68, col: 5, offset: 2227},
						run: (*parser).callonEqualsCondition14,
						expr: &seqExpr{
							pos: position{line: 68, col: 5, offset: 2227},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 68, col: 5, offset: 2227},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 68, col: 9, offset: 2231},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 68, col: 11, offset: 2233},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 68, col: 16, offset: 2238},
										name: "EqualsConditionNoParens",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 68, col: 40, offset: 2262},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 68, col: 42, offset: 2264},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 71, col: 5, offset: 2305},
						name: "EqualsConditionNoParens",
					},
				},
			},
		},
		{
			name: "EqualsConditionNoParens",
			pos:  position{line: 73, col: 1, offset: 2330},
			expr: &actionExpr{
				pos: position{line: 74, col: 5, offset: 2358},
				run: (*parser).callonEqualsConditionNoParens1,
				expr: &seqExpr{
					pos: position{line: 74, col: 5, offset: 2358},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 74, col: 5, offset: 2358},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 74, col: 10, offset: 2363},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 74, col: 21, offset: 2374},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 74, col: 23, offset: 2376},
							name: "EqualsComparator",
						},
						&ruleRefExpr{
							pos:  position{line: 74, col: 40, offset: 2393},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 74, col: 42, offset: 2395},
							label: "equals",
							expr: &ruleRefExpr{
								pos:  position{line: 74, col: 49, offset: 2402},
								name: "KeyValue",
							},
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 80, col: 1, offset: 2564},
			expr: &choiceExpr{
				pos: position{line: 81, col: 5, offset: 2579},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 81, col: 5, offset: 2579},
						run: (*parser).callonIdentifier2,
						expr: &seqExpr{
							pos: position{line: 81, col: 5, offset: 2579},
							exprs: []any{
								&notExpr{
									pos: position{line: 81, col: 5, offset: 2579},
									expr: &ruleRefExpr{
										pos:  position{line: 81, col: 6, offset: 2580},
										name: "ReservedWord",
									},
								},
								&labeledExpr{
									pos:   position{line: 81, col: 19, offset: 2593},
									label: "head",
									expr: &ruleRefExpr{
										pos:  position{line: 81, col: 24, offset: 2598},
										name: "IdentifierStart",
									},
								},
								&labeledExpr{
									pos:   position{line: 81, col: 40, offset: 2614},
									label: "tail",
									expr: &zeroOrMoreExpr{
										pos: position{line: 81, col: 45, offset: 2619},
										expr: &ruleRefExpr{
											pos:  position{line: 81, col: 45, offset: 2619},
											name: "IdentifierPart",
										},
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 85, col: 5, offset: 2798},
						name: "ExpressionAttributeName",
					},
				},
			},
		},
		{
			name: "IdentifierStart",
			pos:  position{line: 87, col: 1, offset: 2823},
			expr: &choiceExpr{
				pos: position{line: 88, col: 5, offset: 2843},
				alternatives: []any{
					&charClassMatcher{
						pos:        position{line: 88, col: 5, offset: 2843},
						val:        "[a-zA-Z]",
						ranges:     []rune{'a', 'z', 'A', 'Z'},
						ignoreCase: false,
						inverted:   false,
					},
					&litMatcher{
						pos:        position{line: 89, col: 5, offset: 2856},
						val:        "_",
						ignoreCase: false,
						want:       "\"_\"",
					},
				},
			},
		},
		{
			name: "IdentifierPart",
			pos:  position{line: 91, col: 1, offset: 2861},
			expr: &choiceExpr{
				pos: position{line: 92, col: 5, offset: 2880},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 92, col: 5, offset: 2880},
						name: "IdentifierStart",
					},
					&charClassMatcher{
						pos:        position{line: 93, col: 5, offset: 2900},
						val:        "[0-9]",
						ranges:     []rune{'0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "ExpressionAttributeName",
			pos:  position{line: 95, col: 1, offset: 2907},
			expr: &actionExpr{
				pos: position{line: 96, col: 5, offset: 2935},
				run: (*parser).callonExpressionAttributeName1,
				expr: &seqExpr{
					pos: position{line: 96, col: 5, offset: 2935},
					exprs: []any{
						&notExpr{
							pos: position{line: 96, col: 5, offset: 2935},
							expr: &ruleRefExpr{
								pos:  position{line: 96, col: 6, offset: 2936},
								name: "ReservedWord",
							},
						},
						&labeledExpr{
							pos:   position{line: 96, col: 19, offset: 2949},
							label: "head",
							expr: &litMatcher{
								pos:        position{line: 96, col: 24, offset: 2954},
								val:        "#",
								ignoreCase: false,
								want:       "\"#\"",
							},
						},
						&labeledExpr{
							pos:   position{line: 96, col: 28, offset: 2958},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 96, col: 33, offset: 2963},
								expr: &ruleRefExpr{
									pos:  position{line: 96, col: 33, offset: 2963},
									name: "IdentifierPart",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "KeyValue",
			pos:  position{line: 105, col: 1, offset: 3351},
			expr: &ruleRefExpr{
				pos:  position{line: 106, col: 5, offset: 3364},
				name: "ExpressionAttributeValue",
			},
		},
		{
			name: "ExpressionAttributeValue",
			pos:  position{line: 108, col: 1, offset: 3390},
			expr: &actionExpr{
				pos: position{line: 109, col: 5, offset: 3419},
				run: (*parser).callonExpressionAttributeValue1,
				expr: &seqExpr{
					pos: position{line: 109, col: 5, offset: 3419},
					exprs: []any{
						&notExpr{
							pos: position{line: 109, col: 5, offset: 3419},
							expr: &ruleRefExpr{
								pos:  position{line: 109, col: 6, offset: 3420},
								name: "ReservedWord",
							},
						},
						&labeledExpr{
							pos:   position{line: 109, col: 19, offset: 3433},
							label: "head",
							expr: &litMatcher{
								pos:        position{line: 109, col: 24, offset: 3438},
								val:        ":",
								ignoreCase: false,
								want:       "\":\"",
							},
						},
						&labeledExpr{
							pos:   position{line: 109, col: 28, offset: 3442},
							label: "tail",
							expr: &zeroOrMoreExpr{
								pos: position{line: 109, col: 33, offset: 3447},
								expr: &ruleRefExpr{
									pos:  position{line: 109, col: 33, offset: 3447},
									name: "IdentifierPart",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SKRangeCondition",
			pos:  position{line: 118, col: 1, offset: 3772},
			expr: &choiceExpr{
				pos: position{line: 119, col: 5, offset: 3793},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 119, col: 5, offset: 3793},
						run: (*parser).callonSKRangeCondition2,
						expr: &seqExpr{
							pos: position{line: 119, col: 5, offset: 3793},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 119, col: 5, offset: 3793},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 119, col: 9, offset: 3797},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 119, col: 11, offset: 3799},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 119, col: 15, offset: 3803},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 119, col: 17, offset: 3805},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 119, col: 22, offset: 3810},
										name: "SKRangeConditionNoParens",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 119, col: 47, offset: 3835},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 119, col: 49, offset: 3837},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
								&ruleRefExpr{
									pos:  position{line: 119, col: 53, offset: 3841},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 119, col: 55, offset: 3843},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 123, col: 5, offset: 4019},
						run: (*parser).callonSKRangeCondition14,
						expr: &seqExpr{
							pos: position{line: 123, col: 5, offset: 4019},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 123, col: 5, offset: 4019},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 123, col: 9, offset: 4023},
									name: "_",
								},
								&labeledExpr{
									pos:   position{line: 123, col: 11, offset: 4025},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 123, col: 16, offset: 4030},
										name: "SKRangeConditionNoParens",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 123, col: 41, offset: 4055},
									name: "_",
								},
								&litMatcher{
									pos:        position{line: 123, col: 43, offset: 4057},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 126, col: 5, offset: 4098},
						name: "SKRangeConditionNoParens",
					},
				},
			},
		},
		{
			name: "SKRangeConditionNoParens",
			pos:  position{line: 128, col: 1, offset: 4124},
			expr: &choiceExpr{
				pos: position{line: 129, col: 5, offset: 4153},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 129, col: 5, offset: 4153},
						name: "RangeComparison",
					},
					&ruleRefExpr{
						pos:  position{line: 130, col: 5, offset: 4173},
						name: "BeginsWithFunction",
					},
					&ruleRefExpr{
						pos:  position{line: 131, col: 5, offset: 4196},
						name: "BetweenOperation",
					},
				},
			},
		},
		{
			name: "RangeComparison",
			pos:  position{line: 134, col: 1, offset: 4215},
			expr: &actionExpr{
				pos: position{line: 135, col: 5, offset: 4235},
				run: (*parser).callonRangeComparison1,
				expr: &seqExpr{
					pos: position{line: 135, col: 5, offset: 4235},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 135, col: 5, offset: 4235},
							label: "key",
							expr: &ruleRefExpr{
								pos:  position{line: 135, col: 9, offset: 4239},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 135, col: 20, offset: 4250},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 135, col: 22, offset: 4252},
							label: "comp",
							expr: &ruleRefExpr{
								pos:  position{line: 135, col: 27, offset: 4257},
								name: "RangeComparator",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 135, col: 43, offset: 4273},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 135, col: 45, offset: 4275},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 135, col: 49, offset: 4279},
								name: "KeyValue",
							},
						},
					},
				},
			},
		},
		{
			name: "BeginsWithFunction",
			pos:  position{line: 142, col: 1, offset: 4504},
			expr: &actionExpr{
				pos: position{line: 143, col: 5, offset: 4527},
				run: (*parser).callonBeginsWithFunction1,
				expr: &seqExpr{
					pos: position{line: 143, col: 5, offset: 4527},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 143, col: 5, offset: 4527},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 143, col: 7, offset: 4529},
							name: "BeginsWithToken",
						},
						&ruleRefExpr{
							pos:  position{line: 143, col: 23, offset: 4545},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 143, col: 25, offset: 4547},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 143, col: 29, offset: 4551},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 143, col: 31, offset: 4553},
							label: "key",
							expr: &ruleRefExpr{
								pos:  position{line: 143, col: 35, offset: 4557},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 143, col: 46, offset: 4568},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 143, col: 48, offset: 4570},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 143, col: 52, offset: 4574},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 143, col: 54, offset: 4576},
							label: "prefix",
							expr: &ruleRefExpr{
								pos:  position{line: 143, col: 61, offset: 4583},
								name: "KeyValue",
							},
						},
						&litMatcher{
							pos:        position{line: 143, col: 70, offset: 4592},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "BetweenOperation",
			pos:  position{line: 150, col: 1, offset: 4865},
			expr: &actionExpr{
				pos: position{line: 151, col: 5, offset: 4886},
				run: (*parser).callonBetweenOperation1,
				expr: &seqExpr{
					pos: position{line: 151, col: 5, offset: 4886},
					exprs: []any{
						&notExpr{
							pos: position{line: 151, col: 5, offset: 4886},
							expr: &ruleRefExpr{
								pos:  position{line: 151, col: 6, offset: 4887},
								name: "ReservedWord",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 151, col: 19, offset: 4900},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 151, col: 21, offset: 4902},
							label: "key",
							expr: &ruleRefExpr{
								pos:  position{line: 151, col: 25, offset: 4906},
								name: "Identifier",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 151, col: 36, offset: 4917},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 151, col: 38, offset: 4919},
							name: "BetweenToken",
						},
						&ruleRefExpr{
							pos:  position{line: 151, col: 51, offset: 4932},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 151, col: 53, offset: 4934},
							label: "low",
							expr: &ruleRefExpr{
								pos:  position{line: 151, col: 57, offset: 4938},
								name: "KeyValue",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 151, col: 66, offset: 4947},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 151, col: 68, offset: 4949},
							name: "AndToken",
						},
						&ruleRefExpr{
							pos:  position{line: 151, col: 77, offset: 4958},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 151, col: 79, offset: 4960},
							label: "high",
							expr: &ruleRefExpr{
								pos:  position{line: 151, col: 84, offset: 4965},
								name: "KeyValue",
							},
						},
					},
				},
			},
		},
		{
			name: "EqualsComparator",
			pos:  position{line: 158, col: 1, offset: 5178},
			expr: &litMatcher{
				pos:        position{line: 159, col: 5, offset: 5199},
				val:        "=",
				ignoreCase: false,
				want:       "\"=\"",
			},
		},
		{
			name: "RangeComparator",
			pos:  position{line: 161, col: 1, offset: 5204},
			expr: &choiceExpr{
				pos: position{line: 162, col: 5, offset: 5224},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 162, col: 5, offset: 5224},
						val:        ">=",
						ignoreCase: false,
						want:       "\">=\"",
					},
					&litMatcher{
						pos:        position{line: 163, col: 5, offset: 5233},
						val:        "<=",
						ignoreCase: false,
						want:       "\"<=\"",
					},
					&litMatcher{
						pos:        position{line: 164, col: 5, offset: 5242},
						val:        "<",
						ignoreCase: false,
						want:       "\"<\"",
					},
					&litMatcher{
						pos:        position{line: 165, col: 5, offset: 5250},
						val:        ">",
						ignoreCase: false,
						want:       "\">\"",
					},
				},
			},
		},
		{
			name: "ReservedWord",
			pos:  position{line: 168, col: 1, offset: 5370},
			expr: &choiceExpr{
				pos: position{line: 169, col: 5, offset: 5387},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 169, col: 5, offset: 5387},
						name: "BetweenToken",
					},
					&ruleRefExpr{
						pos:  position{line: 170, col: 5, offset: 5404},
						name: "AndToken",
					},
					&ruleRefExpr{
						pos:  position{line: 171, col: 5, offset: 5417},
						name: "BeginsWithToken",
					},
				},
			},
		},
		{
			name: "BetweenToken",
			pos:  position{line: 173, col: 1, offset: 5434},
			expr: &seqExpr{
				pos: position{line: 173, col: 16, offset: 5449},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 173, col: 16, offset: 5449},
						val:        "between",
						ignoreCase: true,
						want:       "\"BETWEEN\"i",
					},
					&notExpr{
						pos: position{line: 173, col: 27, offset: 5460},
						expr: &ruleRefExpr{
							pos:  position{line: 173, col: 28, offset: 5461},
							name: "IdentifierPart",
						},
					},
				},
			},
		},
		{
			name: "AndToken",
			pos:  position{line: 174, col: 1, offset: 5476},
			expr: &seqExpr{
				pos: position{line: 174, col: 12, offset: 5487},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 174, col: 12, offset: 5487},
						val:        "and",
						ignoreCase: true,
						want:       "\"AND\"i",
					},
					&notExpr{
						pos: position{line: 174, col: 19, offset: 5494},
						expr: &ruleRefExpr{
							pos:  position{line: 174, col: 20, offset: 5495},
							name: "IdentifierPart",
						},
					},
				},
			},
		},
		{
			name: "BeginsWithToken",
			pos:  position{line: 175, col: 1, offset: 5510},
			expr: &seqExpr{
				pos: position{line: 175, col: 18, offset: 5527},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 175, col: 18, offset: 5527},
						val:        "begins_with",
						ignoreCase: true,
						want:       "\"BEGINS_WITH\"i",
					},
					&notExpr{
						pos: position{line: 175, col: 33, offset: 5542},
						expr: &ruleRefExpr{
							pos:  position{line: 175, col: 34, offset: 5543},
							name: "IdentifierPart",
						},
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 177, col: 1, offset: 5559},
			expr: &zeroOrMoreExpr{
				pos: position{line: 178, col: 5, offset: 5578},
				expr: &charClassMatcher{
					pos:        position{line: 178, col: 5, offset: 5578},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
	},
}

func (c *current) onStart1(expr any) (any, error) {

	return expr, nil

}

func (p *parser) callonStart1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStart1(stack["expr"])
}

func (c *current) onKeyConditionExpression2(pk, sk any) (any, error) {
	return fromPKSK(pk, sk, c.paramsFromStore().TableKeys)

}

func (p *parser) callonKeyConditionExpression2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKeyConditionExpression2(stack["pk"], stack["sk"])
}

func (c *current) onKeyConditionExpression11(sk, pk any) (any, error) {
	return fromPKSK(pk, sk, c.paramsFromStore().TableKeys)

}

func (p *parser) callonKeyConditionExpression11() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKeyConditionExpression11(stack["sk"], stack["pk"])
}

func (c *current) onKeyConditionExpression20(left, right any) (any, error) {

	return c.resolveAmbiguousKeyCondition(left, right)

}

func (p *parser) callonKeyConditionExpression20() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKeyConditionExpression20(stack["left"], stack["right"])
}

func (c *current) onKeyConditionExpression29(pk any) (any, error) {
	//! important that this is last, order matters in PEG
	return fromPKSK(pk, nil, c.paramsFromStore().TableKeys)

}

func (p *parser) callonKeyConditionExpression29() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKeyConditionExpression29(stack["pk"])
}

func (c *current) onPKCondition1(eq any) (any, error) {
	equal := astutil.CastTo[*rawEqualCondition](eq)
	return equal.toPKCond(c.paramsFromStore().TableKeys)

}

func (p *parser) callonPKCondition1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPKCondition1(stack["eq"])
}

func (c *current) onEqualsCondition2(expr any) (any, error) {
	// can handle gracefully but DDB doesn't so we fail here with same err msg
	return expr, fmt.Errorf("The expression has redundant parentheses;")

}

func (p *parser) callonEqualsCondition2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqualsCondition2(stack["expr"])
}

func (c *current) onEqualsCondition14(expr any) (any, error) {
	return expr, nil

}

func (p *parser) callonEqualsCondition14() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqualsCondition14(stack["expr"])
}

func (c *current) onEqualsConditionNoParens1(name, equals any) (any, error) {
	n := astutil.CastTo[ast.Identifier](name)
	eq := astutil.CastTo[ast.Value](equals)
	return &rawEqualCondition{n, eq}, nil

}

func (p *parser) callonEqualsConditionNoParens1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEqualsConditionNoParens1(stack["name"], stack["equals"])
}

func (c *current) onIdentifier2(head, tail any) (any, error) {
	name := astutil.HeadTailString(head, tail)
	return ast.RawName{name}, verifyIdentifierAgainstTable(name, c.paramsFromStore().TableKeys)

}

func (p *parser) callonIdentifier2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier2(stack["head"], stack["tail"])
}

func (c *current) onExpressionAttributeName1(head, tail any) (any, error) {
	alias := string(c.text)
	resolved, found := c.paramsFromStore().ExpressionKeyNames[alias]
	if !found {
		return nil, fmt.Errorf("unresolved expression attribute name %q", alias)
	}
	return ast.NewExpressionAttributeName(string(c.text), resolved), verifyIdentifierAgainstTable(resolved, c.paramsFromStore().TableKeys)

}

func (p *parser) callonExpressionAttributeName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpressionAttributeName1(stack["head"], stack["tail"])
}

func (c *current) onExpressionAttributeValue1(head, tail any) (any, error) {
	alias := string(c.text)
	resolved, found := c.paramsFromStore().ExpressionKeyValues[alias]
	if !found {
		return nil, fmt.Errorf("unresolved expression attribute value %q", alias)
	}
	return ast.NewExpressionAttributeValue(string(c.text), resolved), nil

}

func (p *parser) callonExpressionAttributeValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpressionAttributeValue1(stack["head"], stack["tail"])
}

func (c *current) onSKRangeCondition2(expr any) (any, error) {
	// can handle gracefully but DDB doesn't so we fail here with same err msg
	return expr, fmt.Errorf("The expression has redundant parentheses;")

}

func (p *parser) callonSKRangeCondition2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSKRangeCondition2(stack["expr"])
}

func (c *current) onSKRangeCondition14(expr any) (any, error) {
	return expr, nil

}

func (p *parser) callonSKRangeCondition14() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSKRangeCondition14(stack["expr"])
}

func (c *current) onRangeComparison1(key, comp, val any) (any, error) {
	k := astutil.CastTo[ast.Identifier](key)
	cmp := ast.KeyComparator(string(comp.([]byte)))
	v := astutil.CastTo[ast.Value](val)
	return ast.NewComparisonCondition(k, cmp, v), nil

}

func (p *parser) callonRangeComparison1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRangeComparison1(stack["key"], stack["comp"], stack["val"])
}

func (c *current) onBeginsWithFunction1(key, prefix any) (any, error) {

	// unclear whether `prefix` needs to be an expression attribute value or can be a constant string
	k := astutil.CastTo[ast.Identifier](key)
	pfx := astutil.CastTo[ast.Value](prefix)
	return ast.NewBeginsWithCondition(k, pfx), nil

}

func (p *parser) callonBeginsWithFunction1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBeginsWithFunction1(stack["key"], stack["prefix"])
}

func (c *current) onBetweenOperation1(key, low, high any) (any, error) {
	k := astutil.CastTo[ast.Identifier](key)
	lo := astutil.CastTo[ast.Value](low)
	hi := astutil.CastTo[ast.Value](high)
	return ast.NewBetweenCondition(k, lo, hi), nil

}

func (p *parser) callonBetweenOperation1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBetweenOperation1(stack["key"], stack["low"], stack["high"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
